-- AI research notes and outreach drafts, generated by Gemini from a lead's own
-- scraped fields.
--
-- Drafts are stored, never sent. Sending needs a connected mailbox, which this
-- product does not have, and a human should approve outreach in any case — so
-- the product's job ends at a reviewable draft the user can copy.
--
-- Apply with:
--   npx supabase db query --linked -f supabase/migrations/20260818_lead_drafts.sql

create table if not exists public.lead_drafts (
  id          uuid primary key default gen_random_uuid(),
  lead_id     uuid not null references public.leads(id) on delete cascade,
  user_id     uuid not null references auth.users(id) on delete cascade,
  -- 'research' is account context about the business; 'outreach' is a message
  -- written from that context. Kept in one table because they share a lifetime:
  -- both are disposable, regenerable artefacts of one lead.
  kind        text not null check (kind in ('research', 'outreach')),
  subject     text,
  body        text not null,
  -- Which model actually produced this. When a fallback model answers, the
  -- record should say so rather than implying the primary did.
  model       text,
  created_at  timestamptz not null default now()
);

create index if not exists idx_lead_drafts_lead on public.lead_drafts (lead_id, kind, created_at desc);
create index if not exists idx_lead_drafts_user on public.lead_drafts (user_id, created_at desc);

alter table public.lead_drafts enable row level security;

-- Matches how leads themselves are scoped. The edge function writes with the
-- service role and sets user_id explicitly; these policies govern the browser.
drop policy if exists "Users see own drafts" on public.lead_drafts;
create policy "Users see own drafts" on public.lead_drafts
  for select using (auth.uid() = user_id);

drop policy if exists "Users delete own drafts" on public.lead_drafts;
create policy "Users delete own drafts" on public.lead_drafts
  for delete using (auth.uid() = user_id);
